### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by chaoyangnz** [jyostudio/overload#3]
Is it possible to generate the overloaded function typings?

and how to allow non-class types as the arguments?

I suggest to allow a schema to flexibly  define the argument types, json schema or zod or like.

**Comment by sunwanxin213** [comment]
@chaoyangnz 您好！很高兴收到您的反馈！
我将依次回答您的问题：
1、是否可以生成重载函数类型。
很抱歉，我没太理解您的意思，或许您可以写一段您希望的用法Demo？能更好的帮助我理解您的意图。😊

2、目前暂不支持非类类型作为参数，但已经在考虑中了。比如您提出的建议。

针对您提出的建议：允许灵活定义参数类型，比如 json schema，在目前的大架构下是可以扩展的，但这样会增大代码体量，或许会作为一种可选插件提供。

如果您有更好的建议或希望参与实施，欢迎持续与我讨论。
希望您用的愉快！❤

**Comment by sunwanxin213** [comment]
@chaoyangnz 另外，您的 Issue 标题似乎是 “TypeScript 支持”，我似乎无法将标题和内容进行关联。
如果可以的话，还望您能稍微描述下其中的关联性，以便于我更好的支持您的需要。感谢您的配合~🌹

**Comment by sunwanxin213** [comment]
已支持 JSON Schema，请参阅 README 文档。
先关闭此 ISSUE，如果您有其他问题，可开新的 ISSUE，感谢~

**Comment by sunwanxin213** [comment]
补充一下，README 中的 Demo，如果您不使用编译工具。
则请将 "@jyostudio/overload/dist/jsonSchema.js" 替换成绝对路径 "https://unpkg.com/@jyostudio/overload/dist/jsonSchema.js"
